---
    - name: Test playbook to display and mask credential used for authentication
      hosts: all
      gather_facts: no
      vars: 
      - ansible_password: 123456
      tasks:
        - name: Show the connection method used
          debug:
            msg: "Connection method is {{ ansible_connection }}"
    
        - name: Mask the SSH password (if any)
          debug:
            msg: "SSH password: {{ ansible_ssh_pass | default('No password set') | regex_replace('.*', '***') }}"
    
        - name: Mask the WinRM password (if any)
          debug:
            msg: "WinRM password: {{ ansible_password }} ansible user: {{ ansible_user | default ('myname') }}"
